package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.BuildType
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'BuildDebug'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("BuildDebug")
    name = "Build Debug"

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        gradle {
            tasks = "clean build"
            buildFile = ""
            param("teamcity.tool.jacoco", "%teamcity.tool.jacoco.DEFAULT%")
        }
    }

    dependencies {
        snapshot(RelativeId("AndroidLint")) {
        }
        snapshot(RelativeId("Detekt")) {
        }
        snapshot(RelativeId("Ktlint")) {
        }
    }
}))

