name: Auto Approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: |
      (
        (github.actor == 'renovate' || github.actor == 'igorwojda') &&
        (github.event.pull_request.user.login == 'renovate' || github.event.pull_request.user.login == 'igorwojda') &&
        (github.event.pull_request.head.repo.full_name == github.repository)
      )
    steps:
      - uses: hmarr/auto-approve-action@v4
