name: Auto Approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: |
      github.actor == 'renovate' || github.actor == 'igorwojda'
    steps:
      - uses: hmarr/auto-approve-action@v4
